runtime: nodejs20
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  NODE_ENV: "production"
  # This is the correct format for the MONGO_URI in app.yaml
  MONGO_URI: "mongodb+srv://bhanusanjay123_db_user:Sanjayraina12@cluster0.n7lxupo.mongodb.net/?appName=Cluster0"